import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { test } from 'node:test';

const homeSource = readFileSync(new URL('../src/pages/HomePage.tsx', import.meta.url), 'utf8');
const homeStyles = readFileSync(new URL('../src/styles/home.css', import.meta.url), 'utf8');
const loginSource = readFileSync(new URL('../src/pages/LoginPage.tsx', import.meta.url), 'utf8');
const registerSource = readFileSync(new URL('../src/pages/RegisterPage.tsx', import.meta.url), 'utf8');
const layoutSource = readFileSync(new URL('../src/components/AppLayout.tsx', import.meta.url), 'utf8');
const commandPaletteSource = readFileSync(new URL('../src/components/GlobalCommandPalette.tsx', import.meta.url), 'utf8');
const backendConfigSource = readFileSync(new URL('../../backend/app/core/config.py', import.meta.url), 'utf8');
const backendMainSource = readFileSync(new URL('../../backend/app/main.py', import.meta.url), 'utf8');
const latexSource = readFileSync(new URL('../../backend/app/services/latex_processor.py', import.meta.url), 'utf8');
const arxivCacheSource = readFileSync(new URL('../../backend/app/services/arxiv_pdf_cache.py', import.meta.url), 'utf8');

test('current product surfaces use AstraLoom branding', () => {
  for (const source of [homeSource, loginSource, registerSource, layoutSource, commandPaletteSource]) {
    assert.match(source, /AstraLoom/);
    assert.doesNotMatch(source, /Auto-Research-DS/);
  }
});

test('home page exposes AstraLoom workflow and navigation entries', () => {
  assert.match(homeSource, /className="astraloom-title">AstraLoom/);
  assert.match(homeSource, /把论文、证据、灵感和实验线索编织成一张清晰的科研星图/);
  assert.match(homeSource, /workflowNodes/);
  assert.match(homeSource, /Papers/);
  assert.match(homeSource, /Ideas/);
  assert.match(homeSource, /Experiments/);
  assert.match(homeSource, /Writing/);
  assert.match(homeSource, /navigate\(`\/papers\?q=\$\{encodeURIComponent\(searchValue\.trim\(\)\)\}`\)/);
  for (const path of ['/chat', '/papers', '/research', '/writing']) {
    assert.match(homeSource, new RegExp(`path: '${path}'`));
  }
});

test('home styles define AstraLoom constellation and loom visual hooks', () => {
  for (const className of [
    'astraloom-home',
    'astraloom-hero',
    'astraloom-star',
    'loom-stage',
    'loom-node',
    'astraloom-action',
    'astraloom-feature-card',
  ]) {
    assert.match(homeStyles, new RegExp(`\\.${className}`));
  }
});

test('backend runtime identifiers use AstraLoom', () => {
  assert.match(backendConfigSource, /APP_NAME: str = "AstraLoom"/);
  assert.match(backendMainSource, /description="AstraLoom 智能科研工作台 API"/);
  assert.match(latexSource, /Generated by AstraLoom/);
  assert.match(arxivCacheSource, /AstraLoom\/1\.0/);
});
