import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { test } from 'node:test';

const homeSource = readFileSync(new URL('../src/pages/HomePage.tsx', import.meta.url), 'utf8');
const homeStyles = readFileSync(new URL('../src/styles/home.css', import.meta.url), 'utf8');
const loginSource = readFileSync(new URL('../src/pages/LoginPage.tsx', import.meta.url), 'utf8');
const registerSource = readFileSync(new URL('../src/pages/RegisterPage.tsx', import.meta.url), 'utf8');
const layoutSource = readFileSync(new URL('../src/components/AppLayout.tsx', import.meta.url), 'utf8');
const commandPaletteSource = readFileSync(new URL('../src/components/GlobalCommandPalette.tsx', import.meta.url), 'utf8');
const backendConfigSource = readFileSync(new URL('../../backend/app/core/config.py', import.meta.url), 'utf8');
const backendMainSource = readFileSync(new URL('../../backend/app/main.py', import.meta.url), 'utf8');
const latexSource = readFileSync(new URL('../../backend/app/services/latex_processor.py', import.meta.url), 'utf8');
const arxivCacheSource = readFileSync(new URL('../../backend/app/services/arxiv_pdf_cache.py', import.meta.url), 'utf8');

test('current product surfaces use AstraLoom branding', () => {
  for (const source of [homeSource, loginSource, registerSource, layoutSource, commandPaletteSource]) {
    assert.match(source, /AstraLoom/);
    assert.doesNotMatch(source, /Auto-Research-DS/);
  }
});

test('home page exposes AstraLoom workflow and navigation entries', () => {
  assert.match(homeSource, /className="hero-title">AstraLoom/);
  assert.match(homeSource, /新一代 AI 驱动的自动化科研工作流系统/);
  assert.match(homeSource, /AI 对话/);
  assert.match(homeSource, /论文库/);
  assert.match(homeSource, /研究方向/);
  assert.match(homeSource, /写作助手/);
  assert.match(homeSource, /navigate\(`\/papers\?q=\$\{encodeURIComponent\(searchValue\.trim\(\)\)\}`\)/);
  for (const path of ['/chat', '/papers', '/research', '/writing']) {
    assert.match(homeSource, new RegExp(`path: '${path}'`));
  }
});

test('home styles define the restored AstraLoom home visual hooks', () => {
  for (const className of [
    'hero-section',
    'particles-bg',
    'hero-title',
    'quick-action-btn',
    'stats-section',
    'features-section',
    'feature-card-v2',
    'footer-section',
  ]) {
    assert.match(homeStyles, new RegExp(`\\.${className}`));
  }
  assert.doesNotMatch(homeStyles, /loom-stage/);
  assert.doesNotMatch(homeStyles, /astraloom-feature-card/);
});

test('backend runtime identifiers use AstraLoom', () => {
  assert.match(backendConfigSource, /APP_NAME: str = "AstraLoom"/);
  assert.match(backendMainSource, /description="AstraLoom 智能科研工作台 API"/);
  assert.match(latexSource, /Generated by AstraLoom/);
  assert.match(arxivCacheSource, /AstraLoom\/1\.0/);
});
